name: expense_tracker
description: "This project is to track day to day expenses"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  framework:
    path: framework
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0 # for easy navigation
  flutter_bloc: ^8.1.3 # state management
  get_it: ^7.6.4 # Dependency injection.
  injectable: ^2.3.2
  sqflite: ^2.0.0+4
  path: ^1.8.0 # db join 2 paths
  freezed_annotation: ^2.4.1 # Code
  flutter_svg: ^2.0.9 # Render SVG images.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  freezed: ^2.4.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/