name: framework
description: Framework for all Flutter apps.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0" # Dart version compatibility
  flutter: "3.19.6" # Flutter version compatibility

dependencies: 
  bloc: ^8.1.0 # State management
  equatable: ^2.0.5
  fast_immutable_collections: ^7.4.1
  freezed_annotation: ^2.4.1
  meta: ^1.8.0
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^4.0.0
  freezed: ^2.4.1
  build_runner: ^2.3.3
